### ISSUE TITLE
CDN for whole network

### ISSUE THREAD

**Issue by isaumya** [wmark/CDN-Linker#44]
Hi,
I have a small feature request for subdomain based wp multisite network. If you guys can code it so that one cdn can be used for the whole network, it would be great. Currently only W3TC have this feature.
I think if CDNLinker can also do it it would be great for multisite owners :)

**Comment by wmark** [comment]
Thanks!

Please email me any future feature requests (not this one, I've received it already ;-) ) and don't open Github issues for them. I use the latter, as per the README, for confirmed bugs only.

Multisite configurations are not part of the open-source version of CDN Linker.

**Comment by isaumya** [comment]
I didnt find the page to purchase the pro version.
